name: Compile

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    defaults:
      run:
        shell: powershell
    runs-on: windows-latest
    steps:
      - name: Compile
        uses: xefino/mql4-compiler@v0.1.4
        with:
          version: 1370
          path: .\Slave_4.mq4
          verbose: true
      - name: Check directory
        if: always()
        run: |
          Get-ChildItem -Force
