name: Compile

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: fx31337/mql-compile-action@master
        with:
          mt-version: 4.0.0.1359
          path: 'Slave_4.mq4'
          include: '.'
          ignore-warnings: false
          verbose: true
