name: Compile

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    defaults:
      run:
        shell: powershell
    runs-on: windows-latest
    steps:
    - name: Compile
      uses: xefino/mql4-compiler@v0.3.0
      with:
        version: 1370
        path: .\Slave_4.mq4
        verbose: true
    - name: Check directory
      if: always()
      run: |
        Get-ChildItem -Force
    - name: Commit Compiled Files
      run: |
        git --version
        git config --global user.email "$(git log -n 1 --pretty=format:%ae)"
        git config --global user.name "$(git log -n 1 --pretty=format:%an)"
        git add *.ex4
        git diff-index --quiet HEAD || git commit -m "${{ github.event.head_commit.message }}"
    - name: Push Compiled Files
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
