name: Compile

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    defaults:
      run:
        shell: powershell
    runs-on: windows-latest
    steps:
      - name: Compile
        uses: fx31337/mql-compile-action@master
        with:
          include: .
          mt-version: 4.0.0.1370
          path: '.\Slave_4.mq4'
          init-platform: true
          verbose: true
