name: Compile

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    defaults:
      run:
        shell: powershell
    runs-on: windows-latest
    steps:
    - name: Get AppData Directory
      run: echo ("APPDATA_DIR=" + $env:APPDATA) >> $env:GITHUB_ENV
    - name: Checkout
      uses: actions/checkout@v2
    - name: Checkout mql-http
      uses: actions/checkout@v2
      with:
        repository: xefino/mql-http
        path: ${{ env.APPDATA_DIR }}\MetaQuotes\Terminal\B4A57AAB059458B669EF812D12D27772\MQL5\Include
    - name: Checkout mql5-json
      uses: actions/checkout@v2
      with:
        repository: xefino/mql5-json
        path: ${{ env.APPDATA_DIR }}\MetaQuotes\Terminal\B4A57AAB059458B669EF812D12D27772\MQL5\Include
    - name: Checkout order-send-common-mt4
      uses: actions/checkout@v2
      with:
        repository: xefino/order-send-common-mt4
        path: ${{ env.APPDATA_DIR }}\MetaQuotes\Terminal\B4A57AAB059458B669EF812D12D27772\MQL5\Include
    - name: Compile
      uses: fx31337/mql-compile-action@v1
      with:
        path: '.\Slave_4.mq4'
        include: '.' 
        verbose: true
    - name: Check directory
      if: always()
      run: |
        Get-ChildItem -Force
    - name: Commit Compiled Files
      run: |
        git --version
        git config --global user.email "$(git log -n 1 --pretty=format:%ae)"
        git config --global user.name "$(git log -n 1 --pretty=format:%an)"
        git add *.ex4
        if (git diff-index --quiet HEAD) {
          git commit -m "${{ github.event.head_commit.message }}"
        }
    - name: Push Compiled Files
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
