name: Compile

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Create Log File
        run: |
          touch .\results.log
      - uses: fx31337/mql-compile-action@master
        with:
          mt-version: 4.0.0.1320
          path: 'Slave_4.mq4'
          include: '.'
          log-file: .\results.log
          ignore-warnings: false
          verbose: true
      - name: Print Log File
        run: |
          cat .\results.log
